# Site settings
title: "Lambda++: Functional Sequence Library in C++"
email: ananyak@andrew, jezimmer@andrew
description: > # this means to ignore newlines until "baseurl:"
  A parallel sequence library for C++ with support for operations like map,
  reduce, and scan, which take higher order functions and automatically detects
  hardware configurations to adapt performance in a highly-parallel manner.
baseurl: "/lambda--" # the subpath of your site, e.g. /blog/
url: "https://ananyakumar.github.io" # the base hostname & protocol for your site

exclude:
  - README.md
  - LICENSE
  - Gemfile.lock
  - Gemfile

permalink: /:title/

# Build settings
markdown: redcarpet

redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - autolink
    - disable_indented_code_blocks
    - strikethrough
    - footnotes
    - with_toc_data
    - smart

# -- custom metadata --
github_usernames:
  - ananyakumar
  - jez
